@echo off
echo Starting Medicircle Connect Backend...
echo Installing dependencies...
pip install -r backend/requirements.txt
echo Starting Server (from root)...
uvicorn backend.main:app --reload --port 8000
pause
